/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-03-11 at 07:27:39 UTC 
 * Modify at your own risk.
 */

package org.ctoolkit.api.agent.model;

/**
 * Model definition for ChangeJob.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Toolkit Migration Agent. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ChangeJob extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mapReduceJobId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer processedErrorItems;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer processedItems;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stackTrace;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String state;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer totalItems;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public ChangeJob setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMapReduceJobId() {
    return mapReduceJobId;
  }

  /**
   * @param mapReduceJobId mapReduceJobId or {@code null} for none
   */
  public ChangeJob setMapReduceJobId(java.lang.String mapReduceJobId) {
    this.mapReduceJobId = mapReduceJobId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getProcessedErrorItems() {
    return processedErrorItems;
  }

  /**
   * @param processedErrorItems processedErrorItems or {@code null} for none
   */
  public ChangeJob setProcessedErrorItems(java.lang.Integer processedErrorItems) {
    this.processedErrorItems = processedErrorItems;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getProcessedItems() {
    return processedItems;
  }

  /**
   * @param processedItems processedItems or {@code null} for none
   */
  public ChangeJob setProcessedItems(java.lang.Integer processedItems) {
    this.processedItems = processedItems;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStackTrace() {
    return stackTrace;
  }

  /**
   * @param stackTrace stackTrace or {@code null} for none
   */
  public ChangeJob setStackTrace(java.lang.String stackTrace) {
    this.stackTrace = stackTrace;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getState() {
    return state;
  }

  /**
   * @param state state or {@code null} for none
   */
  public ChangeJob setState(java.lang.String state) {
    this.state = state;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTotalItems() {
    return totalItems;
  }

  /**
   * @param totalItems totalItems or {@code null} for none
   */
  public ChangeJob setTotalItems(java.lang.Integer totalItems) {
    this.totalItems = totalItems;
    return this;
  }

  @Override
  public ChangeJob set(String fieldName, Object value) {
    return (ChangeJob) super.set(fieldName, value);
  }

  @Override
  public ChangeJob clone() {
    return (ChangeJob) super.clone();
  }

}
