/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-07-26 at 09:50:53 UTC 
 * Modify at your own risk.
 */

package org.ctoolkit.api.agent.model;

/**
 * Model definition for MetadataAudit.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Toolkit Migration Agent. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MetadataAudit extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String action;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime createDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String createdBy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String operation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String ownerId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime updateDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String updatedBy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String userDisplayName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String userPhotoUrl;

  /**
   * @return value or {@code null} for none
   */
  public String getAction() {
    return action;
  }

  /**
   * @param action action or {@code null} for none
   */
  public MetadataAudit setAction(String action) {
    this.action = action;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreateDate() {
    return createDate;
  }

  /**
   * @param createDate createDate or {@code null} for none
   */
  public MetadataAudit setCreateDate(com.google.api.client.util.DateTime createDate) {
    this.createDate = createDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getCreatedBy() {
    return createdBy;
  }

  /**
   * @param createdBy createdBy or {@code null} for none
   */
  public MetadataAudit setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public MetadataAudit setId(Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getOperation() {
    return operation;
  }

  /**
   * @param operation operation or {@code null} for none
   */
  public MetadataAudit setOperation(String operation) {
    this.operation = operation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getOwnerId() {
    return ownerId;
  }

  /**
   * @param ownerId ownerId or {@code null} for none
   */
  public MetadataAudit setOwnerId(String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getUpdateDate() {
    return updateDate;
  }

  /**
   * @param updateDate updateDate or {@code null} for none
   */
  public MetadataAudit setUpdateDate(com.google.api.client.util.DateTime updateDate) {
    this.updateDate = updateDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getUpdatedBy() {
    return updatedBy;
  }

  /**
   * @param updatedBy updatedBy or {@code null} for none
   */
  public MetadataAudit setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getUserDisplayName() {
    return userDisplayName;
  }

  /**
   * @param userDisplayName userDisplayName or {@code null} for none
   */
  public MetadataAudit setUserDisplayName(String userDisplayName) {
    this.userDisplayName = userDisplayName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getUserPhotoUrl() {
    return userPhotoUrl;
  }

  /**
   * @param userPhotoUrl userPhotoUrl or {@code null} for none
   */
  public MetadataAudit setUserPhotoUrl(String userPhotoUrl) {
    this.userPhotoUrl = userPhotoUrl;
    return this;
  }

  @Override
  public MetadataAudit set(String fieldName, Object value) {
    return (MetadataAudit) super.set(fieldName, value);
  }

  @Override
  public MetadataAudit clone() {
    return (MetadataAudit) super.clone();
  }

}
