/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-07-26 at 09:50:53 UTC 
 * Modify at your own risk.
 */

package org.ctoolkit.api.agent.model;

/**
 * Model definition for MigrationJob.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Toolkit Migration Agent. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MigrationJob extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String jobId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String jobUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer processedErrorItems;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer processedItems;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String stackTrace;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String state;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer totalItems;

  /**
   * @return value or {@code null} for none
   */
  public Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public MigrationJob setId(Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getJobId() {
    return jobId;
  }

  /**
   * @param jobId jobId or {@code null} for none
   */
  public MigrationJob setJobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getJobUrl() {
    return jobUrl;
  }

  /**
   * @param jobUrl jobUrl or {@code null} for none
   */
  public MigrationJob setJobUrl(String jobUrl) {
    this.jobUrl = jobUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Integer getProcessedErrorItems() {
    return processedErrorItems;
  }

  /**
   * @param processedErrorItems processedErrorItems or {@code null} for none
   */
  public MigrationJob setProcessedErrorItems(Integer processedErrorItems) {
    this.processedErrorItems = processedErrorItems;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Integer getProcessedItems() {
    return processedItems;
  }

  /**
   * @param processedItems processedItems or {@code null} for none
   */
  public MigrationJob setProcessedItems(Integer processedItems) {
    this.processedItems = processedItems;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getStackTrace() {
    return stackTrace;
  }

  /**
   * @param stackTrace stackTrace or {@code null} for none
   */
  public MigrationJob setStackTrace(String stackTrace) {
    this.stackTrace = stackTrace;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getState() {
    return state;
  }

  /**
   * @param state state or {@code null} for none
   */
  public MigrationJob setState(String state) {
    this.state = state;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Integer getTotalItems() {
    return totalItems;
  }

  /**
   * @param totalItems totalItems or {@code null} for none
   */
  public MigrationJob setTotalItems(Integer totalItems) {
    this.totalItems = totalItems;
    return this;
  }

  @Override
  public MigrationJob set(String fieldName, Object value) {
    return (MigrationJob) super.set(fieldName, value);
  }

  @Override
  public MigrationJob clone() {
    return (MigrationJob) super.clone();
  }

}
