/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-07-26 at 09:50:53 UTC 
 * Modify at your own risk.
 */

package org.ctoolkit.api.agent.model;

/**
 * Model definition for MigrationBatch.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Toolkit Migration Agent. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MigrationBatch extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime createDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MigrationItem> items;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String jobId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private MigrationJob jobInfo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String source;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String target;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime updateDate;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreateDate() {
    return createDate;
  }

  /**
   * @param createDate createDate or {@code null} for none
   */
  public MigrationBatch setCreateDate(com.google.api.client.util.DateTime createDate) {
    this.createDate = createDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public MigrationBatch setId(Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MigrationItem> getItems() {
    return items;
  }

  /**
   * @param items items or {@code null} for none
   */
  public MigrationBatch setItems(java.util.List<MigrationItem> items) {
    this.items = items;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getJobId() {
    return jobId;
  }

  /**
   * @param jobId jobId or {@code null} for none
   */
  public MigrationBatch setJobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public MigrationJob getJobInfo() {
    return jobInfo;
  }

  /**
   * @param jobInfo jobInfo or {@code null} for none
   */
  public MigrationBatch setJobInfo(MigrationJob jobInfo) {
    this.jobInfo = jobInfo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public MigrationBatch setName(String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getSource() {
    return source;
  }

  /**
   * @param source source or {@code null} for none
   */
  public MigrationBatch setSource(String source) {
    this.source = source;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getTarget() {
    return target;
  }

  /**
   * @param target target or {@code null} for none
   */
  public MigrationBatch setTarget(String target) {
    this.target = target;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getUpdateDate() {
    return updateDate;
  }

  /**
   * @param updateDate updateDate or {@code null} for none
   */
  public MigrationBatch setUpdateDate(com.google.api.client.util.DateTime updateDate) {
    this.updateDate = updateDate;
    return this;
  }

  @Override
  public MigrationBatch set(String fieldName, Object value) {
    return (MigrationBatch) super.set(fieldName, value);
  }

  @Override
  public MigrationBatch clone() {
    return (MigrationBatch) super.clone();
  }

}
