/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-07-26 at 09:50:53 UTC 
 * Modify at your own risk.
 */

package org.ctoolkit.api.agent.model;

/**
 * Model definition for PropertyMetaData.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Toolkit Migration Agent. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PropertyMetaData extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String kind;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String namespace;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String property;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String type;

  /**
   * @return value or {@code null} for none
   */
  public String getKind() {
    return kind;
  }

  /**
   * @param kind kind or {@code null} for none
   */
  public PropertyMetaData setKind(String kind) {
    this.kind = kind;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getNamespace() {
    return namespace;
  }

  /**
   * @param namespace namespace or {@code null} for none
   */
  public PropertyMetaData setNamespace(String namespace) {
    this.namespace = namespace;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getProperty() {
    return property;
  }

  /**
   * @param property property or {@code null} for none
   */
  public PropertyMetaData setProperty(String property) {
    this.property = property;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public PropertyMetaData setType(String type) {
    this.type = type;
    return this;
  }

  @Override
  public PropertyMetaData set(String fieldName, Object value) {
    return (PropertyMetaData) super.set(fieldName, value);
  }

  @Override
  public PropertyMetaData clone() {
    return (PropertyMetaData) super.clone();
  }

}
